sudo: required
services:
  - docker
script: 
  - docker ps 
  - heroku auth:token
  - docker build -t registry.heroku.com/kafka-docker-compose/kafka .
  - heroku container:login
  - heroku container:push kafka --app=kafka-docker-compose
  - heroku container:release kafka --app=kafka-docker-compose