sudo: required
services:
  - docker
script: 
  - docker ps 
  - heroku auth:token
  - docker build -t registry.heroku.com/kafka-docker-compose/web .
  - heroku container:login
  - heroku container:push web --app=kafka-docker-compose
  - heroku container:release web --app=kafka-docker-compose
